const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH COLLECTIONS START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH COLLECTIONS SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH COLLECTIONS FAILURE",
};

export default ShopActionTypes;
